services:
  postgres:
    image: postgres:17
    container_name: aspectexams-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: aspectexams
    volumes:
      - /home/tricia/docker-volumes/aspectexams/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
