services:
  postgres:
    image: postgres:17
    container_name: aspectexams-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: aspectexams
    volumes:
      - /home/tricia/docker-volumes/aspectexams/pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspectexams-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://docker:docker@postgres:5432/aspectexams?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ['node', 'server.js']

volumes:
  pgdata:
